-- MySQL Script generated by MySQL Workbench
-- Tue Feb 17 11:57:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProgSENA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProgSENA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProgSENA` DEFAULT CHARACTER SET utf8 ;
USE `ProgSENA` ;

-- -----------------------------------------------------
-- Table `ProgSENA`.`TITULO_PROGRAMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`TITULO_PROGRAMA` (
  `titpro_id` INT NOT NULL,
  `titpro_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`titpro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`PROGRAMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`PROGRAMA` (
  `prog_codigo` INT NOT NULL,
  `prog_denominacion` VARCHAR(100) NOT NULL,
  `TIT_PROGRAMA_titpro_id` INT NOT NULL,
  `prog_tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`prog_codigo`),
  INDEX `fk_PROGRAMA_TIPO_PROGRAMA_idx` (`TIT_PROGRAMA_titpro_id` ASC) VISIBLE,
  CONSTRAINT `fk_PROGRAMA_TIPO_PROGRAMA`
    FOREIGN KEY (`TIT_PROGRAMA_titpro_id`)
    REFERENCES `ProgSENA`.`TITULO_PROGRAMA` (`titpro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`COMPETENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`COMPETENCIA` (
  `comp_id` INT NOT NULL,
  `comp_nombre_corto` VARCHAR(30) NOT NULL,
  `comp_horas` INT NOT NULL,
  `comp_nombre_unidad_competencia` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`comp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`CENTRO_FORMACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`CENTRO_FORMACION` (
  `cent_id` INT NOT NULL,
  `cent_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cent_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`INSTRUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`INSTRUCTOR` (
  `inst_id` INT NOT NULL,
  `inst_nombres` VARCHAR(45) NOT NULL,
  `inst_apellidos` VARCHAR(45) NOT NULL,
  `inst_correo` VARCHAR(45) NOT NULL,
  `inst_telefono` BIGINT(10) NOT NULL,
  `CENTRO_FORMACION_cent_id` INT NOT NULL,
  `inst_password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`inst_id`),
  INDEX `fk_INSTRUCTOR_CENTRO_FORMACION1_idx` (`CENTRO_FORMACION_cent_id` ASC) VISIBLE,
  CONSTRAINT `fk_INSTRUCTOR_CENTRO_FORMACION1`
    FOREIGN KEY (`CENTRO_FORMACION_cent_id`)
    REFERENCES `ProgSENA`.`CENTRO_FORMACION` (`cent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`COMPETxPROGRAMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`COMPETxPROGRAMA` (
  `PROGRAMA_prog_id` INT NOT NULL,
  `COMPETENCIA_comp_id` INT NOT NULL,
  PRIMARY KEY (`PROGRAMA_prog_id`, `COMPETENCIA_comp_id`),
  INDEX `fk_COMPETxPROGRAMA_COMPETENCIA1_idx` (`COMPETENCIA_comp_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMPETxPROGRAMA_PROGRAMA1`
    FOREIGN KEY (`PROGRAMA_prog_id`)
    REFERENCES `ProgSENA`.`PROGRAMA` (`prog_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPETxPROGRAMA_COMPETENCIA1`
    FOREIGN KEY (`COMPETENCIA_comp_id`)
    REFERENCES `ProgSENA`.`COMPETENCIA` (`comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`COORDINACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`COORDINACION` (
  `coord_id` INT NOT NULL,
  `coord_descripcion` VARCHAR(45) NOT NULL,
  `CENTRO_FORMACION_cent_id` INT NOT NULL,
  `coord_nombre_coordinador` VARCHAR(45) NOT NULL,
  `coord_correo` VARCHAR(45) NOT NULL,
  `coord_password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`coord_id`),
  INDEX `fk_COORDINACION_CENTRO_FORMACION1_idx` (`CENTRO_FORMACION_cent_id` ASC) VISIBLE,
  CONSTRAINT `fk_COORDINACION_CENTRO_FORMACION1`
    FOREIGN KEY (`CENTRO_FORMACION_cent_id`)
    REFERENCES `ProgSENA`.`CENTRO_FORMACION` (`cent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`FICHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`FICHA` (
  `fich_id` INT NOT NULL,
  `PROGRAMA_prog_id` INT NOT NULL,
  `INSTRUCTOR_inst_id_lider` INT NOT NULL,
  `fich_jornada` VARCHAR(20) NOT NULL,
  `COORDINACION_coord_id` INT NOT NULL,
  `fich_fecha_ini_lectiva` DATE NOT NULL,
  `fich_fecha_fin_lectiva` DATE NOT NULL,
  PRIMARY KEY (`fich_id`),
  INDEX `fk_FICHA_PROGRAMA1_idx` (`PROGRAMA_prog_id` ASC) VISIBLE,
  INDEX `fk_FICHA_INSTRUCTOR1_idx` (`INSTRUCTOR_inst_id_lider` ASC) VISIBLE,
  INDEX `fk_FICHA_COORDINACION1_idx` (`COORDINACION_coord_id` ASC) VISIBLE,
  CONSTRAINT `fk_FICHA_PROGRAMA1`
    FOREIGN KEY (`PROGRAMA_prog_id`)
    REFERENCES `ProgSENA`.`PROGRAMA` (`prog_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FICHA_INSTRUCTOR1`
    FOREIGN KEY (`INSTRUCTOR_inst_id_lider`)
    REFERENCES `ProgSENA`.`INSTRUCTOR` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FICHA_COORDINACION1`
    FOREIGN KEY (`COORDINACION_coord_id`)
    REFERENCES `ProgSENA`.`COORDINACION` (`coord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`SEDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`SEDE` (
  `sede_id` INT NOT NULL,
  `sede_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sede_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`AMBIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`AMBIENTE` (
  `amb_id` VARCHAR(5) NOT NULL,
  `amb_nombre` VARCHAR(45) NULL,
  `SEDE_sede_id` INT NOT NULL,
  PRIMARY KEY (`amb_id`),
  INDEX `fk_AMBIENTE_SEDE1_idx` (`SEDE_sede_id` ASC) VISIBLE,
  CONSTRAINT `fk_AMBIENTE_SEDE1`
    FOREIGN KEY (`SEDE_sede_id`)
    REFERENCES `ProgSENA`.`SEDE` (`sede_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`ASIGNACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`ASIGNACION` (
  `INSTRUCTOR_inst_id` INT NOT NULL,
  `asig_fecha_ini` DATETIME NOT NULL,
  `asig_fecha_fin` DATETIME NOT NULL,
  `FICHA_fich_id` INT NOT NULL,
  `AMBIENTE_amb_id` VARCHAR(5) NOT NULL,
  `COMPETENCIA_comp_id` INT NOT NULL,
  `ASIG_ID` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_ASIGNACION_INSTRUCTOR1_idx` (`INSTRUCTOR_inst_id` ASC) VISIBLE,
  INDEX `fk_ASIGNACION_FICHA1_idx` (`FICHA_fich_id` ASC) VISIBLE,
  INDEX `fk_ASIGNACION_AMBIENTE1_idx` (`AMBIENTE_amb_id` ASC) VISIBLE,
  INDEX `fk_ASIGNACION_COMPETENCIA1_idx` (`COMPETENCIA_comp_id` ASC) VISIBLE,
  PRIMARY KEY (`ASIG_ID`),
  CONSTRAINT `fk_ASIGNACION_INSTRUCTOR1`
    FOREIGN KEY (`INSTRUCTOR_inst_id`)
    REFERENCES `ProgSENA`.`INSTRUCTOR` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNACION_FICHA1`
    FOREIGN KEY (`FICHA_fich_id`)
    REFERENCES `ProgSENA`.`FICHA` (`fich_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNACION_AMBIENTE1`
    FOREIGN KEY (`AMBIENTE_amb_id`)
    REFERENCES `ProgSENA`.`AMBIENTE` (`amb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNACION_COMPETENCIA1`
    FOREIGN KEY (`COMPETENCIA_comp_id`)
    REFERENCES `ProgSENA`.`COMPETENCIA` (`comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`DETALLExASIGNACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`DETALLExASIGNACION` (
  `ASIGNACION_ASIG_ID` INT NOT NULL,
  `detasig_hora_ini` DATETIME NOT NULL,
  `detasig_hora_fin` DATETIME NOT NULL,
  `detasig_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`detasig_id`),
  INDEX `fk_DETALLExASIGNACION_ASIGNACION1_idx` (`ASIGNACION_ASIG_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLExASIGNACION_ASIGNACION1`
    FOREIGN KEY (`ASIGNACION_ASIG_ID`)
    REFERENCES `ProgSENA`.`ASIGNACION` (`ASIG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgSENA`.`INSTRU_COMPETENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProgSENA`.`INSTRU_COMPETENCIA` (
  `INSTRUCTOR_inst_id` INT NOT NULL,
  `COMPETxPROGRAMA_PROGRAMA_prog_id` INT NOT NULL,
  `COMPETxPROGRAMA_COMPETENCIA_comp_id` INT NOT NULL,
  `inscomp_vigencia` DATE NOT NULL,
  `inscomp_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`inscomp_id`),
  INDEX `fk_INSTRU_COMPETENCIA_INSTRUCTOR1_idx` (`INSTRUCTOR_inst_id` ASC) VISIBLE,
  INDEX `fk_INSTRU_COMPETENCIA_COMPETxPROGRAMA1_idx` (`COMPETxPROGRAMA_PROGRAMA_prog_id` ASC, `COMPETxPROGRAMA_COMPETENCIA_comp_id` ASC) VISIBLE,
  CONSTRAINT `fk_INSTRU_COMPETENCIA_INSTRUCTOR1`
    FOREIGN KEY (`INSTRUCTOR_inst_id`)
    REFERENCES `ProgSENA`.`INSTRUCTOR` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INSTRU_COMPETENCIA_COMPETxPROGRAMA1`
    FOREIGN KEY (`COMPETxPROGRAMA_PROGRAMA_prog_id` , `COMPETxPROGRAMA_COMPETENCIA_comp_id`)
    REFERENCES `ProgSENA`.`COMPETxPROGRAMA` (`PROGRAMA_prog_id` , `COMPETENCIA_comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
